# Generated by Django 5.1.7 on 2026-01-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='e.g. 1.0.0', max_length=50)),
                ('force_update', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, help_text='Message to show in the update dialog')),
                ('store_url', models.URLField(blank=True, help_text='Link to Play Store / App Store')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
    ]
